name: Workflow A

on:
    workflow_dispatch: 

jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "Hello"
            
            - name: use B
              uses: ././github/workflows/b.yml
            #   secrets: inherit

