name: Workflow B

on:
  workflow_call:
    inputs:
      VAL:
        description: val
        default: HAHA
        type: string
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print context
        run: echo "${{ toJson(github) }}"

      - name: Print input
        run: echo "${{ inputs.VAL }}"

      - name: Print if called
        if: inputs.VAL != ''
        run: echo "Workflow called - ${{ github.event_name }}"

      - name: Print if dispatched
        if: inputs.VAL == ''
        run: echo "Workflow dispatched - ${{ github.event_name }}"
